version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
      
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend    
      
  bionicpro-auth:
    build:
      context: ./BionicPRO.Auth/BionicPRO.Auth
      dockerfile: Dockerfile
    container_name: bionicpro-auth
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Keycloak__Authority: http://keycloak:8080/realms/reports-realm
      Keycloak__TokenEndpoint: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/token
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
      
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    command: --copy-service --loglevel debug


volumes:
  postgres_data:
  ldap_data:
  ldap_config:
